import{A as f,S as d,N as L,a as E,E as S,b as k,c as v,K as q,i as g}from"./assets/vendor-li3fMhde.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const C=document.querySelector(".about-accordion-container");new f(C,{openOnInit:[0],showMultiple:!1,duration:500,elementClass:"about-ac",panelClass:"about-ac-panel",triggerClass:"about-ac-btn"});new d(".about-skills",{navigation:{nextEl:".about-swiper-btn"},keyboard:{enabled:!0,onlyInViewport:!0,pageUpDown:!0},mousewheel:{invert:!0},grabCursor:!0,touchEventsTarget:"wrapper",slideClass:"about-skills-item",slideActiveClass:"about-skills-item-accent",wrapperClass:"about-skills-list",slidesPerView:2,loopedSlides:2,spaceBetween:1,loop:!0,breakpoints:{768:{slidesPerView:3},1440:{slidesPerView:5,loopedSlides:5}}});new d(".projects-swiper-container",{modules:[L,E,S],direction:"horizontal",loop:!1,slidesPerView:1,spaceBetween:10,mousewheel:!0,effect:"cards",grabCursor:!0,keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".projects-swiper-btn-next",prevEl:".projects-swiper-btn-prev",disabledClass:"projects-swiper-btn-disabled"}});const I=document.querySelector(".accordion");new f(I,{openOnInit:[],showMultiple:!1,duration:500,elementClass:"accordion-item",panelClass:"accordion-content",triggerClass:"btn-svg-opn"});const p=document.querySelectorAll(".btn-svg-opn");p.forEach(e=>{e.addEventListener("click",()=>{p.forEach(o=>{o!==e&&o.classList.remove("rotate")}),e.classList.toggle("rotate")})});const j=document.querySelector("#covers"),l=document.querySelector(".covers-wrapper");function x(e){e.forEach(o=>{o.isIntersecting?l.classList.add("animated"):l.classList.remove("animated")})}const M=new IntersectionObserver(x,{root:null,threshold:0});M.observe(j);function P(e){if(e.preventDefault(),e.target.nodeName!=="IMG")return;const o=e.target.currentSrc,r=k.create(`<div class="covers-full-image-wrapper">
      <img
        src="${o}"
        alt="${e.target.alt}"
        class="covers-full-image"
      />
      <button class="covers-close-button"></button>
    </div>`,{onShow:t=>{window.addEventListener("keydown",n);const s=t.element().querySelector(".covers-close-button");s&&s.addEventListener("click",()=>{t.close()})},onClose:t=>{window.removeEventListener("keydown",n)}});r.show();function n(t){t.code==="Escape"&&r.close()}}l.addEventListener("click",P);const w=document.querySelector(".js-reviews-box-list");v.defaults.baseURL="https://portfolio-js.b.goit.study/api";async function B(){try{return(await v.get("/reviews")).data}catch{g.error({message:"Error fetching reviews. Please try again later.",position:"topRight"});return}}async function O(){try{const e=await B();if(!e||e.length===0){w.innerHTML='<li class="reviews-list-card">Not Found</li>';return}const o=e.map(r=>`
          <li class="swiper-slide reviews-list-card">
            <img src="${r.avatar_url}" 
                 loading="lazy" 
                 alt="${r.author}" 
                 class="reviews-card-img" 
                 width="48" height="48">
            <div class="reviews-card-desc">
              <h3 class="reviews-card-subtitle">${r.author}</h3>
              <div class="reviews-card-text">${r.review}</div>
            </div>
          </li>
        `).join("");w.innerHTML=o}catch{g.error({message:"Error rendering reviews. Please try again later.",position:"topRight"})}}async function V(){await O(),new d(".reviews-swiper",{modules:[q],direction:"horizontal",slidesPerView:1,spaceBetween:16,navigation:{nextEl:".js-reviews-btn-next",prevEl:".js-reviews-btn-previous"},keyboard:{enabled:!0,onlyInViewport:!0},breakpoints:{320:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:4}}})}V();const T=document.querySelector(".work-t-modal"),a=document.querySelector(".work-t-form"),u=document.querySelector(".work-t-modal"),D=document.querySelector(".work-t-input-email"),N=e=>{e.preventDefault();const o="https://portfolio-js.b.goit.study/api/requests";(t=>{const s={method:"post",body:JSON.stringify(t),headers:{"Content-Type":"application/json"}};return fetch(`${o}`,s).then(i=>{if(!i.ok)throw new Error(i.status);return i.json()})})({email:"client@gmail.com",comment:"comments"}).then(t=>{T.classList.add("js-is-open"),a.reset(),console.log(t)}).catch(t=>{D.classList.add("js-input-email"),alert("Invalid Email"),console.log(t)});const n={email:a.elements.user_email.value.trim(),comments:a.elements.user_comments.value.trim()};console.log(n)};a.addEventListener("submit",N);const $=e=>{u.classList.add("disabled")};u.addEventListener("click",$);document.addEventListener("keydown",e=>{e.key==="Escape"&&A()});const A=e=>{u.classList.add("disabled")},h=document.querySelector(".js-menu-container"),R=document.querySelector(".js-open-menu"),z=document.querySelector(".js-close-menu"),m=document.querySelector(".menu-click"),b=document.querySelector(".header-menu-click"),U=document.querySelectorAll(".mobile-nav-link"),c=document.querySelector(".header");function _(){h.classList.add("is-open")}function y(){h.classList.remove("is-open")}function H(){m.classList.remove("open")}R.addEventListener("click",_);z.addEventListener("click",y);U.forEach(e=>{e.addEventListener("click",o=>{const r=o.target.getAttribute("href");document.querySelector(r).scrollIntoView({behavior:"smooth"}),y()})});b.addEventListener("click",()=>{m.classList.toggle("open")});document.addEventListener("click",e=>{!m.contains(e.target)&&!b.contains(e.target)&&H()});function K(){window.scrollY>50?(c.classList.add("fixed"),localStorage.setItem("headerState","fixed")):(c.classList.remove("fixed"),localStorage.setItem("headerState","default"))}window.addEventListener("load",()=>{localStorage.getItem("headerState")==="fixed"?(c.classList.add("fixed"),window.scrollTo(0,window.scrollY)):c.classList.remove("fixed")});window.addEventListener("scroll",K);document.getElementById("ToTop").addEventListener("click",function(e){e.preventDefault(),window.scrollTo({top:0,behavior:"smooth"})});document.getElementById("OnBottom").addEventListener("click",function(e){e.preventDefault(),document.getElementById("work-together").scrollIntoView({behavior:"smooth"})});
//# sourceMappingURL=index.js.map
